# Generated by Django 2.2.18 on 2021-04-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_auto_20210225_1103"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="sources",
            field=models.TextField(blank=True),
        ),
    ]
