# Generated by Django 3.2.7 on 2021-11-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0004_feedback_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="vote",
            field=models.CharField(
                blank=True,
                choices=[("YES", "Yes"), ("NO", "No")],
                max_length=100,
            ),
        ),
    ]
