# Generated by Django 3.2.10 on 2022-02-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0011_replace_emblem_with_emblem_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="localparty",
            name="contact_page_url",
            field=models.URLField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name="localparty",
            name="youtube_profile_url",
            field=models.URLField(blank=True, max_length=800),
        ),
    ]
