# Generated by Django 2.2.18 on 2021-02-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news_mentions", "0002_ballotnewsarticle_publisher"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ballotnewsarticle",
            options={"get_latest_by": "modified"},
        ),
    ]
