# Generated by Django 2.2.20 on 2021-06-04 12:45

from django.db import migrations
from django.utils import timezone

REFORM_UK_ID = "party:7931"
CHANGE_DATE = timezone.datetime(2021, 1, 6).date()


def add_party_name(apps, schema_editor):

    PersonPost = apps.get_model("people", "PersonPost")

    for candidacy in PersonPost.objects.select_related(
        "party", "post_election__election"
    ).iterator():
        party_id = candidacy.party.party_id
        election_date = candidacy.post_election.election.election_date

        if party_id == REFORM_UK_ID and election_date < CHANGE_DATE:
            candidacy.party_name = "Brexit Party"
        else:
            candidacy.party_name = candidacy.party.party_name

        candidacy.save()


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0037_auto_20210604_1245"),
    ]

    operations = [
        migrations.RunPython(
            code=add_party_name, reverse_code=migrations.RunPython.noop
        )
    ]
