# Generated by Django 3.2.7 on 2022-01-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0039_auto_20210928_1303"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="blog_url",
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
