# Generated by Django 3.2.10 on 2022-03-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0040_person_blog_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="DummyCandidacy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("people.personpost",),
        ),
        migrations.CreateModel(
            name="DummyPerson",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("people.person",),
        ),
    ]
