# Generated by Django 3.2.10 on 2022-03-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0012_add_youtube_and_contact_url"),
        ("people", "0041_dummycandidacy_dummyperson"),
    ]

    operations = [
        migrations.AddField(
            model_name="personpost",
            name="previous_party_affiliations",
            field=models.ManyToManyField(
                blank=True,
                related_name="alliated_memberships",
                to="parties.Party",
            ),
        ),
    ]
