# Generated by Django 2.2.18 on 2021-03-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hustings", "0004_auto_20170602_1031"),
    ]

    operations = [
        migrations.AlterField(
            model_name="husting",
            name="postevent_url",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
