# Generated by Django 2.2.18 on 2021-04-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hustings", "0005_auto_20210326_1111"),
    ]

    operations = [
        migrations.AlterField(
            model_name="husting",
            name="postevent_url",
            field=models.URLField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name="husting",
            name="url",
            field=models.URLField(max_length=800),
        ),
    ]
