# Generated by Django 2.2.18 on 2021-04-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hustings", "0006_increase_url_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="husting",
            name="postevent_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="husting",
            name="url",
            field=models.URLField(),
        ),
    ]
