# Generated by Django 2.2.20 on 2021-04-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hustings", "0007_auto_20210419_1539"),
    ]

    operations = [
        migrations.AlterField(
            model_name="husting",
            name="postevent_url",
            field=models.URLField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name="husting",
            name="url",
            field=models.URLField(max_length=800),
        ),
    ]
