# Generated by Django 3.2.10 on 2022-03-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hustings", "0008_url_max_length"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="husting",
            name="postcode",
        ),
        migrations.AlterField(
            model_name="husting",
            name="location",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
    ]
