# Generated by Django 2.2.17 on 2021-02-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("elections", "0033_auto_20210210_1422"),
    ]

    operations = [
        migrations.CreateModel(
            name="Referendum",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("council_name", models.CharField(max_length=255)),
                ("area_name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("answer_one", models.CharField(blank=True, max_length=255)),
                ("answer_two", models.CharField(blank=True, max_length=255)),
                ("council_url", models.URLField(blank=True, max_length=255)),
                (
                    "answer_one_campaign_url",
                    models.URLField(blank=True, max_length=255),
                ),
                (
                    "answer_two_campaign_url",
                    models.URLField(blank=True, max_length=255),
                ),
                (
                    "ballots",
                    models.ManyToManyField(
                        related_name="referendums", to="elections.PostElection"
                    ),
                ),
            ],
        ),
    ]
