# Generated by Django 2.2.18 on 2021-02-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20170526_1448"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loggedpostcode",
            options={"get_latest_by": "modified"},
        ),
    ]
