# Generated by Django 2.2.17 on 2021-01-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0030_post_organization_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="area_id",
        ),
        migrations.RemoveField(
            model_name="post",
            name="area_name",
        ),
        migrations.RemoveField(
            model_name="post",
            name="role",
        ),
    ]
