# Generated by Django 2.2.13 on 2021-01-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0030_post_organization_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="division_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CED", "County Electoral Division"),
                    ("COP", "Isles of Scilly Parish"),
                    ("DIW", "District Ward"),
                    ("EUR", "European Parliament Region"),
                    ("LAC", "London Assembly Constituency"),
                    ("LBW", "London Borough Ward"),
                    ("LGE", "NI Electoral Area"),
                    ("MTW", "Metropolitan District Ward"),
                    ("NIE", "NI Assembly Constituency"),
                    ("SPC", "Scottish Parliament Constituency"),
                    ("SPE", "Scottish Parliament Region"),
                    ("UTE", "Unitary Authority Electoral Division"),
                    ("UTW", "Unitary Authority Ward"),
                    ("WAC", "Welsh Assembly Constituency"),
                    ("WAE", "Welsh Assembly Region"),
                    ("WMC", "Westminster Parliamentary Constituency"),
                ],
                max_length=3,
            ),
        ),
    ]
