# Generated by Django 2.2.17 on 2021-01-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0030_post_organization_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="division_type",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
