# Generated by Django 2.2.13 on 2021-02-10 11:55

from django.db import migrations


def forwards(apps, schema_editor):
    Post = apps.get_model("elections", "Post")
    count, _ = Post.objects.filter(ynr_id="").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0031_post_division_type"),
    ]

    operations = [
        migrations.RunPython(
            code=forwards, reverse_code=migrations.RunPython.noop
        )
    ]
