# Generated by Django 2.2.13 on 2021-02-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0032_auto_20210210_1155"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="ynr_id",
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False
            ),
        ),
    ]
