# Generated by Django 2.2.18 on 2021-04-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0033_auto_20210210_1422"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="election",
            options={"ordering": ["election_date", "election_weight"]},
        ),
    ]
