# Generated by Django 3.2 on 2021-09-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0034_update_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="metadata",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="postelection",
            name="metadata",
            field=models.JSONField(null=True),
        ),
    ]
