# Generated by Django 3.2.10 on 2022-03-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0036_add_timestamps"),
    ]

    operations = [
        migrations.CreateModel(
            name="DummyPostElection",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("elections.postelection",),
        ),
    ]
