# Generated by Django 3.2.13 on 2022-05-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0037_dummypostelection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postelection",
            name="winner_count",
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
